services:
  tor:
    build: ./tor
    container_name: onionpress-tor
    environment:
      - ONIONPRESS_VERSION=${ONIONPRESS_VERSION:-unknown}
      - ONIONPRESS_CELLAR=${ONIONPRESS_CELLAR:-0}
    volumes:
      - arti-state:/var/lib/arti/
      - onionpress-data:/var/lib/onionpress
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - onionpress-network
    ports:
      - "127.0.0.1:9050:9050"

  wordpress:
    build: ./wordpress
    container_name: onionpress-wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_CONFIG_EXTRA=
          $$scheme = 'http';
          if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') $$scheme = 'https';
          define('WP_HOME', $$scheme . '://' . $$_SERVER['HTTP_HOST']);
          define('WP_SITEURL', $$scheme . '://' . $$_SERVER['HTTP_HOST']);
          define('FORCE_SSL_ADMIN', false);
          define('COOKIE_DOMAIN', $$_SERVER['HTTP_HOST']);
    volumes:
      - wordpress-data:/var/www/html
      - onionpress-data:/var/lib/onionpress
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - onionpress-network
    ports:
      - "127.0.0.1:8080:80"

  db:
    image: mariadb:latest
    container_name: onionpress-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - onionpress-network

  tor-polling:
    build: ./tor
    container_name: onionpress-tor-polling
    environment:
      - POLLING_ONLY=1
      - ONIONPRESS_VERSION=${ONIONPRESS_VERSION:-unknown}
    restart: unless-stopped
    networks:
      - onionpress-network
    profiles:
      - cellar

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: onionpress-cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - onionpress-network
    depends_on:
      - wordpress
    restart: unless-stopped
    profiles:
      - cloudflare

volumes:
  arti-state:
    name: onionpress-arti-state
  wordpress-data:
    name: onionpress-wordpress-data
  db-data:
    name: onionpress-db-data
  onionpress-data:
    name: onionpress-persistent-data

networks:
  onionpress-network:
    name: onionpress-network
    driver: bridge
